spring:
  datasource:
    url: jdbc:mysql://localhost:3306/prod_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: prod_user
    password: prod_password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false