server:
  port: 8080 # Port par défaut
spring:
  application:
    name: springboot-microservices-tests
  profiles:
    active: @spring.profiles.active@
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    cache: false

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html